site_name: My Docs(Test)
theme:
  name: 'material'
nav:
- Home: index.md
- User Guide:
    - Writing your docs: User Guide/writing-your-docs.md
    - Styling your docs: User Guide/styling-your-docs.md
- About:
    - License: About/license.md
    - Release Notes: About/release-notes.md